06-01-avatar solution
js-tasks-ru/htmlcss-20220811_mogvay-73 pull request #11
Opened 2022-09-13 00:22 UTC by Mogvay-web

2022-09-13 00:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-13 22:54 UTC, GSemikozov requested changes

2022-09-13 22:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar_img{
.avatar_img -> .avatar__img

2022-09-16 10:32 UTC, Mogvay-web commented on 06-lection4/01-avatar/index.html
> +            <img class="avatar__img" src="/06-lection4/01-avatar/public/avatar-200.jpg" alt="avatar">
Исправил имя класса

2022-09-16 10:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-16 10:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-16 20:30 UTC, GSemikozov approved these changes

2022-09-16 20:30 UTC, merged