accordion solution
js-tasks-ru/htmlcss-20220811_mogvay-73 pull request #4
Opened 2022-08-21 17:37 UTC by Mogvay-web

2022-08-21 17:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-22 08:55 UTC, GSemikozov requested changes

2022-08-22 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
жестко не фиксируем, можно удалить

2022-08-22 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +
не хватает паддингов

2022-08-22 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0px 24px 32px;
паддинги задаем 1 раз на уровне .accordion__item

2022-08-22 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 0px 48.69px 32px 32px;
паддинги будут заданы на уровне .accordion__item, здесь эти марджины не нужны (разве что сверху)

2022-08-22 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item">
элементы блока не могут существовать вне блока, поэтому все item-ы надо завернуть в div с классом accordion

2022-08-24 14:18 UTC, GSemikozov requested changes

2022-08-24 14:18 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 48.69px 24px 32px;
дробные значения не используем (косяк в дизайне)

2022-08-29 09:49 UTC, Mogvay-web commented on 03-lection1/02-accordion/accordion.css
>      border-radius: 8px;
Округлил отступ до большего значения

2022-08-29 09:50 UTC, Mogvay-web commented on 03-lection1/02-accordion/accordion.css
>  .accordion__summary {
Убрал свои закомментированные области с комментарием здесь и ниже

2022-08-29 10:12 UTC, Mogvay-web commented on 03-lection1/02-accordion/accordion.css
> -    margin-bottom: 8px; /*От content до нижней границы аккордеона 32px, поэтому изменил на 8 (+24px из item)*/
Убрал лишний закомментированный код

2022-08-29 10:13 UTC, Mogvay-web commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
Убрал лишние комментарии с пояснением

2022-08-29 10:14 UTC, Mogvay-web commented on 03-lection1/02-accordion/accordion.css
> -
Убрал закомментированный кусок кода с пояснением

2022-08-30 14:21 UTC, GSemikozov approved these changes

2022-08-30 14:21 UTC, merged